### ISSUE TITLE
短视频存储找不到文件

### ISSUE THREAD

**Issue by wanghaibao123** [a483210/MagicCamera-ImageReader#1]
短视频拍摄完成后之后没有存储路径

**Comment by a483210** [comment]
额，我并没有录制视频，你在左上角看到的那个缩略图就是最终效果，如果你需要最终录制成为视频，你可以使用MediaCodec或者ffmpeg编码成h264

**Comment by wanghaibao123** [comment]
哦，这样啊，可以私聊交流吗，这块感觉挺难的

**Comment by a483210** [comment]
这块你可以看下[yasea](https://github.com/begeekmyfriend/yasea)的[SrsEncoder](https://github.com/begeekmyfriend/yasea/blob/master/library/src/main/java/net/ossrs/yasea/SrsEncoder.java)，写的很详细

**Comment by wanghaibao123** [comment]
哦哦，，我还有一个小问题，，就是之前你推荐的那个视频滤镜和你这个一样，不知道你改动哪里了，你的很流程，你推荐的那个好卡，

**Comment by a483210** [comment]
额，你说的是美颜吗？你说我推荐的是[MagicCamera]()吗？

**Comment by a483210** [comment]
额，你说的美颜吗？那个我推荐的是指[MagicCamera](https://github.com/wuhaoyu1990/MagicCamera)还是什么？

**Comment by wanghaibao123** [comment]
嗯啊，就是这个，，感觉你们的一样，但是你的流畅很多，那个很卡，但是可以生成文件，，有点找不到你们的区别

**Comment by a483210** [comment]
[MagicCamera-ImageReader](https://github.com/a483210/MagicCamera-ImageReader)我没有修改啊，唯一有修改的可能就是摄像头的分辨率比他小我是480x640的。
我新发的文章[《Android 关于美颜/滤镜 利用PBO从OpenGL录制视频》](http://www.jianshu.com/p/3bc4db687546)倒是修改了下，在录制的过程中不需要过2次滤镜了。
如果觉得卡的话，还可以通过替换[MagicBeautyFilter](https://github.com/a483210/MagicCamera-ImageReader/blob/master/magicfilter/src/main/java/com/seu/magicfilter/filter/advanced/MagicBeautyFilter.java)的片段着色器为[beauty_low.glsl](https://github.com/a483210/myExample/blob/master/FilterRecord/library/src/main/res/raw/beauty_low.glsl)，这样效率能提高很多。

**Comment by wanghaibao123** [comment]
哦，那我好好研究一下，非常感谢

**Comment by wanghaibao123** [comment]
可不可以加一下QQ或者微信啥的

**Comment by a483210** [comment]
你在简书发个简信给我吧

**Comment by wanghaibao123** [comment]
好的
